{% set name = "xeus-cpp" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/compiler-research/xeus-cpp/archive/{{ version }}.tar.gz
  sha256: d6585f711fe1f8697a11f4da5511a51981ca46df13b72761663298fcb5f126e7

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - zlib

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - xeus-zmq >=3.0,<4.0
    - xeus >=5
    - pugixml
    - cpp-argparse
    - nlohmann_json ==3.12.0
    - cppinterop
    - libcurl
  run:
    # Even though nlohmann_json is header-only,
    # it is used at runtime by the c++ interpreter.
    - {{ pin_compatible('nlohmann_json', max_pin='x.x.x') }}
    - libcurl

test:
  requires:
    - jupyter_kernel_test
  commands:
    - test -f ${PREFIX}/bin/xcpp  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xcpp.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/compiler-research/xeus-cpp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for the C++ programming language
  description: Jupyter kernel for the C++ programming languague, based on clang
  doc_url: https://github.com/compiler-research/xeus-cpp
  dev_url: https://github.com/compiler-research/xeus-cpp

extra:
  recipe-maintainers:
    - anutosh491
    - vgvassilev
    - alexander-penev
    - SylvainCorlay
    - JohanMabille
