{% set name = "xeus-cpp" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/compiler-research/xeus-cpp/archive/{{ version }}.tar.gz
  sha256: 352400083227e3ef8f747ddaffe37ca19af6cd760254cb033114ea6027929aec

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}
  ignore_run_exports:
    - zlib

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - zeromq
    - cppzmq >=4.6.0,<5
    - xeus-zmq >=1.0.1,<2.0
    - xeus >=3.0.0,<4
    - xtl >=0.7.7,<0.8
    - pugixml
    - cpp-argparse >=2.9,<3.1
    - nlohmann_json ==3.11.2
    - dirent >=1.21,<2.0  # [win]
    - zlib
    - cppinterop
  run:
    # Even though cppzmq, xtl and nlohmann_json are header-only,
    # they are used at runtime by the c++ interpreter.
    - {{ pin_compatible('cppzmq', max_pin='x.x') }}
    - {{ pin_compatible('xtl', max_pin='x.x') }}
    - {{ pin_compatible('nlohmann_json', max_pin='x.x.x') }}
    - cppinterop

test:
  requires:
    - jupyter_kernel_test
  commands:
    - test -f ${PREFIX}/bin/xcpp  # [unix]
    - if exist %LIBRARY_PREFIX%\bin\xcpp.exe (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/compiler-research/xeus-cpp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for the C++ programming language
  description: Jupyter kernel for the C++ programming languague, based on clang
  doc_url: https://github.com/compiler-research/xeus-cpp
  dev_url: https://github.com/compiler-research/xeus-cpp

extra:
  recipe-maintainers:
    - vgvassilev
    - alexander-penev
    - SylvainCorlay
    - JohanMabille
