context:
  version: "0.7.2"
  build_number: 0

package:
  name: xeus-cpp
  version: ${{ version }}

source:
  url: https://github.com/compiler-research/xeus-cpp/archive/${{ version }}.tar.gz
  sha256: 679f4065490f49d7d5aee4639a0f44e1e70412421f5ad0a029ee21f76fb3e33e

build:
  number: ${{ build_number }}

requirements:
  run_exports:
    - ${{ pin_subpackage('xeus-cpp', upper_bound='x.x') }}
  ignore_run_exports:
    from_package:
      - zlib
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - xeus-zmq >=3.0,<4.0
    - xeus >=5
    - pugixml
    - cpp-argparse
    - nlohmann_json
    - nlohmann_json-abi
    - cppinterop
    - libcurl
  run:
    # Even though nlohmann_json is header-only,
    # it is used at runtime by the c++ interpreter.
    - ${{ pin_compatible('nlohmann_json', upper_bound='x.x.x') }}
    - libcurl

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}bin/xcpp${{ ".exe" if win }}

about:
  homepage: https://github.com/compiler-research/xeus-cpp
  repository: https://github.com/compiler-research/xeus-cpp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for the C++ programming language
  description: Jupyter kernel for the C++ programming languague, based on clang
  documentation: https://github.com/compiler-research/xeus-cpp

extra:
  recipe-maintainers:
    - anutosh491
    - vgvassilev
    - alexander-penev
    - SylvainCorlay
    - JohanMabille
