context:
  version: "0.8.0"
  build_number: 1

package:
  name: xeus-cpp
  version: ${{ version }}

source:
  url: https://github.com/compiler-research/xeus-cpp/archive/${{ version }}.tar.gz
  sha256: 3d3b437799e98dc1d23add165a1c1dff77b1251e19646c18fb5f3ad2bd0c47f5
  patches:
    - 0001-Set-kernel-configuration-as-cache-variables.patch

build:
  number: ${{ build_number }}

requirements:
  run_exports:
    - ${{ pin_subpackage('xeus-cpp', upper_bound='x.x') }}
  ignore_run_exports:
    from_package:
      - zlib
  build:
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
    - cmake
    - if: unix
      then:
        - make
  host:
    - xeus-zmq >=3.0,<4.0
    - xeus >=5
    - pugixml
    - cpp-argparse
    - nlohmann_json
    - nlohmann_json-abi
    - cppinterop
    - libcurl
  run:
    # Even though nlohmann_json is header-only,
    # it is used at runtime by the c++ interpreter.
    - ${{ pin_compatible('nlohmann_json', upper_bound='x.x.x') }}
    - libcurl

tests:
  - package_contents:
      files:
        exists:
          - ${{ "Library/" if win }}bin/xcpp${{ ".exe" if win }}
          - ${{ "Library/" if win }}share/jupyter/kernels/xcpp17/kernel.json
          - ${{ "Library/" if win }}share/jupyter/kernels/xcpp20/kernel.json
          - ${{ "Library/" if win }}share/jupyter/kernels/xcpp23/kernel.json
          - ${{ "Library/" if win }}share/jupyter/kernels/xc11/kernel.json
          - ${{ "Library/" if win }}share/jupyter/kernels/xc17/kernel.json
          - ${{ "Library/" if win }}share/jupyter/kernels/xc23/kernel.json
  - if: unix
    then:
      script:
        - test "$(jq -r '.env.PATH' share/jupyter/kernels/xc23/kernel.json)" == '${PATH}'
      requirements:
        run:
          - jq

about:
  homepage: https://github.com/compiler-research/xeus-cpp
  repository: https://github.com/compiler-research/xeus-cpp
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter kernel for the C++ programming language
  description: Jupyter kernel for the C++ programming languague, based on clang
  documentation: https://github.com/compiler-research/xeus-cpp

extra:
  recipe-maintainers:
    - anutosh491
    - vgvassilev
    - alexander-penev
    - SylvainCorlay
    - JohanMabille
